-- ============================================
-- 导航站点击统计表（在 Supabase Dashboard → SQL Editor 运行一次即可）
-- ============================================

-- 1. 建表：记录每次链接点击
CREATE TABLE IF NOT EXISTS public.click_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  link_id bigint,          -- links 表里的链接 id
  link_title text,         -- 链接标题
  url text,                -- 点击的目标地址
  referrer text,           -- 来源页面
  user_agent text,         -- 访客浏览器
  clicked_at timestamptz DEFAULT now()
);

-- 2. 开启行级安全
ALTER TABLE public.click_log ENABLE ROW LEVEL SECURITY;

-- 3. 允许前端匿名写入（页面用 anon key 记录点击）
CREATE POLICY "anon_can_insert_click_log"
  ON public.click_log
  FOR INSERT
  TO anon
  WITH CHECK (true);

-- 4. 授予匿名角色插入权限（查询统计用 secret key，不受影响）
GRANT INSERT ON public.click_log TO anon;

-- ============================================
-- 查询示例（用 secret key 查，或直接在 Dashboard 跑）：
--   最近 7 天每天点击量：
--   SELECT date_trunc('day', clicked_at) AS day, count(*) FROM public.click_log GROUP BY 1 ORDER BY 1 DESC;
--   点击最多的链接：
--   SELECT link_title, count(*) FROM public.click_log GROUP BY 1 ORDER BY 2 DESC;
-- ============================================
